### ISSUE TITLE
SDK does not work in python 3.8

### ISSUE THREAD

**Issue by michi88** [wavefrontHQ/wavefront-django-sdk-python#14]
Python 3.8 does not have time.clock anymore (deprecated since python 3.3). 

```
AttributeError: module 'time' has no attribute 'clock'
  File "django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "django/core/handlers/base.py", line 106, in _get_response
    response = middleware_method(request, callback, callback_args, callback_kwargs)
  File "wavefront_django_sdk/middleware.py", line 108, in process_view
    request.wf_cpu_nanos = time.clock()
```
